### ISSUE TITLE
Display review's details

### ISSUE THREAD

**Issue by cintiavazquez** [cintiavazquez/capstone-project#1]
# Value Proposition
**As a** user
**I need** to see the details for products' reviews.
**I need to be able to** receive information about how a product scored

# Description 
![US1 - See review's details](https://user-images.githubusercontent.com/101577838/167100491-8dd4904e-2fe8-4754-84de-4f6a18edb2b9.png)

Acceptance Criteria 
- [x] Product's name is displayed
- [x] Product's rating is displayed
- [x] Product's review is displayed
- [x] Product's location is displayed
- [x] Elements are displayed in a way that is easy to read and where the user can easily identify each piece of information

# Tasks
- [x] Create a branch "display-product"
- [x] Create the data structure (an array of objects in a json file) where the product details are stored
- [x] Create a new component to render the data
- [x] The component receives product details via props
- [x] The component renders the the product details in <h> and <p> tags
- [x] Add component to index.js
- [x] Add component to Storybook
- [x] Apply basic styling to differentiate the elements
- [x] Add test to check if data is rendered 

# Complexity
M

**Comment by doemser** [comment]
Suggestion for more precise wording:
`As a user`
`I need to see details for products' reviews,`
`in order to be able to receive information about how a product scored` 

Looks good!
You could try to specify your task with the data structure even further:
Which kind of data-structure makes sense?
Where do you store it?
