### ISSUE TITLE
Organize Styled Components

### ISSUE THREAD

**Issue by cintiavazquez** [cintiavazquez/capstone-project#11]
---

# Value Proposition

As a Developer
I need to reorganize my styled-components
to get a clearer overview of the file structure

# Description

New file structure for my styled-component files.

# Acceptance Criteria

- [ ] Store all styled components in the same place

# Tasks

(for developers team)

- [x] Create a UI folder to store styled components
- [x] Add styled-component files to the UI folder and update import links

# Complexity
XS
