### ISSUE TITLE
Organize content in pages

### ISSUE THREAD

**Issue by cintiavazquez** [cintiavazquez/capstone-project#14]
---

# Value Proposition

As a user
I need to have the form and my reviews on a separate page
to be able to have a better overview of my reviews

# Description

![US8 - Add navigation](https://user-images.githubusercontent.com/101577838/169010691-6843ca95-7a83-44e6-8034-7d697640bffa.png)

# Acceptance Criteria

- [x] My form and my reviews are on separate pages
- [x] I can easily access those pages via navigation

# Tasks

- [x] Create additional page (for form)
- [x] Create footer component with navigation, add it to app
- [x] Add routing and nav links to redirect to the different pages
- [x] Add navigation component to Storybook

# Complexity
M
