### ISSUE TITLE
Display a map

### ISSUE THREAD

**Issue by cintiavazquez** [cintiavazquez/capstone-project#15]
---

# Value Proposition

**As a** user
**I need** to be able to see the location of vegan products that have been reviewed
**to be able to** find good products and avoid bad ones wherever I am

# Description

<img width="387" alt="US11 - Add map" src="https://user-images.githubusercontent.com/101577838/170998193-61e12295-74dd-49f0-b0db-b7c0715cae77.png">

# Acceptance Criteria

- [x]  For starters implement a non-interactive map
- [x] The maps size has to be set to an appropriate size
- [x] Make sure the map shows content
- [x] If the user allows it, the map centers in their location

# Tasks

- [x] Install required dependencies (leaflet)
- [x] Create a map-component to render the map and add it to the Homepage (dynamic import)
- [x] Use basic attributes for MapContainer from react-leaflet to initialize the map (center, zoom, position) 
- [x] Add a tilelayer (with url and reference to OpenStreetMap) to the MapContainer

# Complexity
M
