### ISSUE TITLE
List all reviews

### ISSUE THREAD

**Issue by cintiavazquez** [cintiavazquez/capstone-project#2]
# Value Proposition
**As a** user
**I need** to see a list of reviews from all users
**I need to be able to** get an overview of all reviews

# Description 

<img width="324" alt="US2 - See list of all reviews" src="https://user-images.githubusercontent.com/101577838/167101709-310b5c81-6c32-4b25-a0f3-f5937dada7e5.png">

Acceptance Criteria 
- [x] Each review should be visually separated  
- [x] Display important details for each product ( as defined in #1)
- [x] All reviewed products should be displayed

# Tasks
- [x] Modify the data structure so that all objects receive an ID
- [x] Create a new component to map over array
- [x] The component receives the array via props
- [x] The list component contains the card component defined in #1 
- [x] Remove single card from the app and add the list component instead
- [x] Apply basic styling to visually isolate each review from all others
- [x] Add to Storybook
- [x] Add test to check if all  products are rendered 

# Complexity
S

**Comment by UrsulaMontag** [comment]
Hey Cintia,
your story looks good, but before this userstory you render only one product card with details and add that product component to your index.js with 'static' props?
If yes, you should describe the shifting of this component to your new list component and all adaptions that have to be made.
