### ISSUE TITLE
Add favourites

### ISSUE THREAD

**Issue by cintiavazquez** [cintiavazquez/capstone-project#20]
---

# Value Proposition

**As a** user,
**I need** to favorite posts
**to be able to** keep track of the products I liked and easily find them again

# Description

![US9 - Add favourite](https://user-images.githubusercontent.com/101577838/169981161-66ae4df7-9389-4551-9088-a0af9d024fea.png)

# Acceptance Criteria

- [x] There is an icon I can click on to favorite a review
- [x] I can see all reviews I marked as favorite on a separate list

# Tasks

(for developers team)

- [x] Add the favorite icon/button to the card component and save the state (favorite/unfavorite)
- [x] Create a new list like the one in #2 that filters the favorited reviews.
- [x] Create a new page where this component is rendered, add new link to nav

# Complexity
- S

**Comment by FranziGraml** [comment]
Hi Cintia,

good User Story :-)
