### ISSUE TITLE
Picture upload

### ISSUE THREAD

**Issue by cintiavazquez** [cintiavazquez/capstone-project#21]
---

# Value Proposition

**As a** user
**I need** to upload pictures of the products I review
**to be able to** easily find them again

# Description
![US10 - Add picture](https://user-images.githubusercontent.com/101577838/169986319-b330eb10-8bda-4d10-bc34-f0d269a7a7bb.png)

# Acceptance Criteria

- [x] I can upload a picture (only one) when filling the add review form
- [x] The picture I upload is shown in my review post after submitting the form
- [x] All pictures in the posts have the same size

# Tasks

- [x] Add URL to the data set
- [x] Define the Next image component so that all pictures can fit into a container of fixed size
- [x] Add Cloudinary and integrate the option to upload in the form component

# Complexity
M

**Comment by marcbendixen** [comment]
Hey 👋 
looks good to me.
 
Maybe you can add a acceptance criteria/task in case someone adds more than one image to upload if possible. Because you need to consider that for the review post card.

**Comment by cintiavazquez** [comment]
Hi Marc!, thanks for your feedback! As for now, I don't want the user to be able to upload more than one photo (at least while I'm not done with my MVP), but I'll take it into account in the future :)
