### ISSUE TITLE
Refurbish

### ISSUE THREAD

**Issue by cintiavazquez** [cintiavazquez/capstone-project#25]
---

# Value Proposition

**As a**user
**I need** the app I'm using to be aesthetically pleasing
**to be able to** have a better user experience

# Description

-

# Acceptance Criteria

- [ ] the page is responsive
- [ ] the colors are harmonious

# Tasks

(for developers team)

- [ ] Add icons for the rating and delete/edit buttons
- [ ] Add flexboxes and containers
- [ ] Add colours to nav and input fields
- [ ] Add modal lightbox
- [ ] Add typography component

# Complexity
L

**Comment by FranziGraml** [comment]
Nice :-)
