### ISSUE TITLE
Display a second map to specify the location of the product when filling the form

### ISSUE THREAD

**Issue by cintiavazquez** [cintiavazquez/capstone-project#30]
---

# Value Proposition

**As a** user
**I need**  to see a map where I can search the location where I bought the product I'm reviewing and see another map with all review's locations
**to be able to** easily save the location where I bought the product without having to know the exact adress and to be able to see reviews around my area

# Description
<img width="723" alt="Screenshot 2022-06-01 at 12 39 42" src="https://user-images.githubusercontent.com/101577838/171394927-03ac8d3e-94aa-4ee3-a834-ec0785c15907.png">

Codesandbox prototype (simplified version, the edit function for the location hasn't been implemented yet):
https://codesandbox.io/s/geocoding-in-leaflet-double-rendering-fixed-e5f23k?file=/LeafletControlGeocoder.jsx

# Acceptance Criteria

- [x] There is a map with a searchbar in the form page.
- [x] If the user allows it, the map in the homepage centers on the user's location
- [x] The user can provide a location via the searchbar in the form
- [x] If the user doesn't provide a location on submit, an alert appears and the data isn't submitted
- [x] In the home page, another map is shown with markers for all existing review locations (and the review data appear as popup when clicking the marker)
- [x] When editing a review, the map in the form doesn't center automatically on the default's location, but in the location that was saved for the review that the user wants to edit.

# Tasks

- [x] Adjust the first map (homepage) so that it maps all review's locations, name, rating, etc
- [x] Render a second map  like the first one and use leaflet control geocoder for the searchbar
- [x] Save the geocoder's positions in an extra state
- [x] Modify the dataset to accept coordinates and modify the submit function so that it provides the coordinates given by the geocoder
- [x] If editmode, center the map on the specific review's coordinates instead of the user's location

# Complexity
XL
