### ISSUE TITLE
Little fixes

### ISSUE THREAD

**Issue by cintiavazquez** [cintiavazquez/capstone-project#31]
---

# Value Proposition

**As a** developer
**I need**  to fix little things in my app
so that it works with no problems and the code is clean

# Description

-Rudimentary changes to the project

# Acceptance Criteria
- The delete modal appears also when deleting from the profile page
- The margin isn't proportional to the view height
- I cant add empty fields using the space bar

# Tasks

- [x] Add nav anchor instead of a button
- [x] Fix page sizing, no vh
- [x] Fix modal component in the profile page
- [x] Fix hookform required field so that one can't add empty spaces

# Complexity

XS
