### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by cintiavazquez** [cintiavazquez/capstone-project#34]
---

# Value Proposition

**As a** developer
**I need** to have a nice landing page
**to be able to** promote my app better

# Description
<img width="501" alt="Screenshot 2022-06-04 at 12 47 27" src="https://user-images.githubusercontent.com/101577838/171995848-69cddc8e-d642-4e9b-8f20-c89a51456f8c.png">

# Acceptance Criteria

- [ ] I see a nice logo that motivates me to use the app
- [ ] I can easily access the  rest of the app

# Tasks

- [ ] Move the homepage to a separate file
- [ ] In the index_js, add a (responsive) logo and a button with routing to access the homepage

# Complexity
S
