### ISSUE TITLE
Adapt layout for wider screens

### ISSUE THREAD

**Issue by cintiavazquez** [cintiavazquez/capstone-project#36]
---

# Value Proposition

**As a** developer
**I need** adapt the layout for wider screens
**to be able to** make efficient use of the available space

# Description

<img width="807" alt="US13 - responsiveness" src="https://user-images.githubusercontent.com/101577838/172058071-c8585450-4a98-461d-a8b2-8a8769b94808.png">

# Acceptance Criteria

- [ ] As soon as two review posts fit beside one another, don't see a single column with reviews anymore, but a two column grid.
- [ ] There is also a bit more space on the top, so that it doesn't look crammed.
- [ ] The form is responsive and gets wider up to a certain point.

# Tasks

(for developers team)

- [ ] Add media queries for the above-mentioned points.

# Complexity
S
