### ISSUE TITLE
Styled components refactoring

### ISSUE THREAD

**Issue by cintiavazquez** [cintiavazquez/capstone-project#39]
---

# Value Proposition

**As a developer**
**I need to write clean code**
**So that the code is maintainable and easy to understand**

# Description

Refactor styled components 

# Acceptance Criteria

- [ ] There should be individual styled components for the divs instead of the current universal DivStyled and DivFlex components, so that the code is easier to read.
- [ ] The color variables don't refer to the colors themselves so that it's not confusing if one reuses them  or other themes.

# Tasks

(for developers team)

- [ ] Create subfolders inside the UI folder to get a clearer overview
- [ ] Divide the big div and divflex into smaller, component-specific styled components.
- [ ] Change the name of the color variables to 2primary, secondary, etc" or similar.

# Complexity
M
