### ISSUE TITLE
Display own reviews

### ISSUE THREAD

**Issue by cintiavazquez** [cintiavazquez/capstone-project#4]
---

# Value Proposition

**As a** ...user
**I need** ...to be able to go over the content I created
**to be able to** ...get an overview of the reviews I myself posted

# Description
<img width="501" alt="US4 - Display own reviews" src="https://user-images.githubusercontent.com/101577838/167001188-cfcbdce8-be29-4208-8c11-e34648193d38.png">

# Acceptance Criteria

- [ ] Each review should be visually separated  
- [ ] Display important details for each review ( see #1)
- [ ] The reviews the user themselves created should be displayed

# Tasks

- [ ] Create a branch "display-my-reviews"
- [ ] Add an user object with usernames to the data structure we defined in #2 
- [ ] Create a new component to filter array for objects containing a certain username
- [ ] The component receives product details via props
- [ ] Add component to the index
- [ ] Add to Storybook
- [ ] Apply basic styling to visually isolate each review from all others (similar than in #2 )
- [ ] Add test to check if the filtered products are rendered 

# Complexity
S
