### ISSUE TITLE
Delete review

### ISSUE THREAD

**Issue by cintiavazquez** [cintiavazquez/capstone-project#5]
---

# Value Proposition

**As a** ...user
**I need** ...to delete my product review
**to be able to** ...manage the content I created

# Description

<img width="982" alt="US5 - Delete review" src="https://user-images.githubusercontent.com/101577838/168806457-18e00d9b-f361-41ee-8d8e-15eaf4d88e76.png">

# Acceptance Criteria

- [x] Delete button is present , recognizable, and clickable
- [x] When the delete button is pressed, a warning pop-up message appears ("Do you really want to delete this review?)
- [x] In the warning message there is an option to delete and an option to get back to the page
- [x] If the get back button is pressed, the user goes back to the previous window
- [x] If the delete button is pressed, the review gets deleted from the reviews' list (#2 )

# Tasks

- [x] Add a delete button with an on-Click event to the review-card
- [x]  Add a filter function that returns the filtered data minus the element with matching ID when the delete is pressed (with Zustand)
- [x] Add a useState that switches from 2 states/functions when pressing the delete button:  standard-mode and delete-mode.
- [x] If the delete-mode is shown, the text ("Do you really want to delete this review?) and two buttons (delete and take me back) are shown.
- [x] Build click events on both buttons: if "take me back" is pressed, toggle to standard-mode, if "delete" is pressed, the element is deleted.
- [x] Add the delete button to Storybook

# Complexity
M
