### ISSUE TITLE
Edit review

### ISSUE THREAD

**Issue by cintiavazquez** [cintiavazquez/capstone-project#6]
--

# Value Proposition

**As a** ...user
**I need** ...to edit my product review
**to be able to** ...manage the content I created

# Description

<img width="332" alt="US6 - Edit review" src="https://user-images.githubusercontent.com/101577838/167123133-9d778109-b293-42f5-b731-9b5665bf4920.png">

# Acceptance Criteria

- [x] Edit button is present , recognizable, and clickable
- [x] When the edit button is pressed, I can edit the whole content of my review
- [x] Save  button is present , recognizable, and clickable
- [x] When the save button is pressed, I can save the latest changes to my review in the reviews list (#2  )

# Tasks

- [x] Create new branch Edit-Review
- [x] Add an edit button with an on-Click event in the review card
- [x] The onClick switches the status when the edit button is pressed (edit mode - default mode)
- [x] If the edit mode is true, give me the form component defined in #3 with a save button instead of submit
- [x] When saving, pass a function that finds the review card by its ID and updates the review list with the new information, and pass another function that toggles the status back to default mode
- [x] If the default mode is true, show the "Edit" text in the button and pass another function that toggles the status back to default mode
- [x] Add the edit button to Storybook

# Complexity
M
